defaults: &defaults
  app_name: "hometaste-dev"
  google_oauth2_app_id: ""
  google_oauth2_secret: ""

development:
  <<: *defaults
  domain: "http:/localhost:3000" #最後 "/" 要拿掉


test:
  <<: *defaults

production:
  <<: *defaults